// Minimal dependency-free production entry point. Deploy behind TLS and set environment variables in the host.
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { dirname, extname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = dirname(fileURLToPath(import.meta.url));
const env = Object.fromEntries((await readFile(join(appRoot, ".env"), "utf8").catch(() => "")).split(/\r?\n/).filter(Boolean).map((line) => { const index=line.indexOf("="); return index > 0 ? [line.slice(0,index).trim(),line.slice(index+1).trim()] : []; }).filter(([key])=>key));
const getEnv = (key) => process.env[key] || env[key] || "";
const config = { apiKey:getEnv("FIREBASE_API_KEY"), authDomain:getEnv("FIREBASE_AUTH_DOMAIN"), projectId:getEnv("FIREBASE_PROJECT_ID"), storageBucket:getEnv("FIREBASE_STORAGE_BUCKET"), messagingSenderId:getEnv("FIREBASE_MESSAGING_SENDER_ID"), appId:getEnv("FIREBASE_APP_ID") };
const json = (response, status, body) => response.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}).end(JSON.stringify(body));
const body = async (request) => { let value=""; for await (const chunk of request) { value+=chunk; if(value.length>100000) throw new Error("Request is too large."); } return JSON.parse(value||"{}"); };
const verify = async (token) => { if(!token || !config.apiKey) return null; const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(config.apiKey)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken:token})}); const data=await response.json(); return response.ok ? data.users?.[0] : null; };
const financialContext = (data) => ({
  transactions:(Array.isArray(data.transactions)?data.transactions:[]).slice(0,500).map(({type,date,category,description,amount})=>({type,date,category,description,amount:Number(amount)})),
  goals:(Array.isArray(data.goals)?data.goals:[]).slice(0,20), bills:(Array.isArray(data.bills)?data.bills:[]).slice(0,50), budget:Number(data.budget)||0,
});
const server=createServer(async(request,response)=>{ try {
  const url=new URL(request.url,"http://localhost");
  if(request.method==="GET" && url.pathname==="/api/config") return json(response,200,{firebase:config});
  if(request.method==="POST" && url.pathname==="/api/assistant") { const user=await verify(request.headers.authorization?.replace(/^Bearer\s+/i,"")); if(!user) return json(response,401,{error:"Sign in again to use the assistant."}); const data=await body(request), prompt=String(data.prompt||"").trim().slice(0,1000); if(!prompt) return json(response,400,{error:"A question is required."}); const key=getEnv("GEMINI_API_KEY"); if(!key) return json(response,503,{error:"AI service is not configured."}); const instruction="You are PocketWise, a professional personal-finance assistant. Use only the supplied user data. Be concise, practical, non-judgmental, and state uncertainty. Do not give legal, tax, investment, or debt advice as certainty. Identify unusual expenses by comparing the user's own records; do not invent transactions. User question: "+prompt+"\nFinancial data: "+JSON.stringify(financialContext(data)); const gemini=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:instruction}]}],generationConfig:{temperature:0.35,maxOutputTokens:700}})}); const result=await gemini.json(); console.error("[Gemini] upstream", gemini.status, gemini.statusText, JSON.stringify(result)); if(!gemini.ok) return json(response,502,{error:"The AI service could not complete that request."}); return json(response,200,{text:result.candidates?.[0]?.content?.parts?.map((part)=>part.text).join("")||"I couldn't generate an answer from the available data."}); }
  if(request.method!=="GET" && request.method!=="HEAD") return json(response,405,{error:"Method not allowed."}); const requested=url.pathname==="/"?"index.html":url.pathname.replace(/^\/+/,""); const path=normalize(join(appRoot,requested)); if(!path.startsWith(appRoot)) return json(response,403,{error:"Forbidden"}); const content=await readFile(path); const type={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".webmanifest":"application/manifest+json"}[extname(path)]||"application/octet-stream"; response.writeHead(200,{"Content-Type":type,"X-Content-Type-Options":"nosniff","Content-Security-Policy":"default-src 'self'; script-src 'self' https://cdn.jsdelivr.net https://www.gstatic.com https://apis.google.com; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://firestore.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src https://*.firebaseapp.com https://accounts.google.com; base-uri 'self'; form-action 'self'"}); response.end(content);
} catch(error) { json(response,error.code==="ENOENT"?404:500,{error:"Request failed."}); } });
server.listen(Number(getEnv("PORT"))||3000,()=>console.log("PocketWise running on http://localhost:"+(Number(getEnv("PORT"))||3000)));
